// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "./routes/layouts/homelayout.tsx": {
    id: "routes/layouts/homelayout";
    page: "/";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layouts/homelayout": typeof import("./app/./routes/layouts/homelayout.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
};